spring.application.name=blogProject
spring.datasource.url=jdbc:postgresql://localhost:5432/blogproject
spring.datasource.username=postgres
spring.datasource.password=ayush
spring.jpa.hibernate.ddl-auto=update

#spring.main.banner-mode=off
#logging.level.root=OFF